src/main/java/com/nike/cerberus/operation/cms/CreateCmsClusterOperation.java
src/main/java/com/nike/cerberus/operation/consul/CreateConsulClusterOperation.java
src/main/java/com/nike/cerberus/operation/gateway/CreateGatewayClusterOperation.java
src/main/java/com/nike/cerberus/operation/vault/CreateVaultClusterOperation.java

Fixing a known issue where if for unforeseen reasons, the CloudFormation stack fails to be created, but we haven't saved the stack id to our configuration bucket yet, leaving us with no reference for the CLI.
These stack operations will now save off the stack id immediately after kicking off the create stack command.

Reorder when the stack id is saved to the configuration bucket

---

src/main/java/com/nike/cerberus/command/cms/CreateCmsConfigCommand.java
src/main/java/com/nike/cerberus/operation/cms/CreateCmsConfigOperation.java

CMS now requires some additional configuration for whatever auth connector will be used.  Auth connectors require additional properties to be wired correctly at runtime.  These changes to the create-cms-config command allow us to pass in additional configuration that will be added to the environment specific configuration file for CMS.
An additional change was made to support the newer property names for JDBC url, user and password.
If the additional properties attempt to override the system defaults that are set automatically, it will be skipped and a warning message emitted.

Support setting arbitrary configuration properties for CMS

---

smaas-cf/smaas/cms-cluster.py

The OSS version of CMS exposes its healthcheck endpoint on 8080, not 8077.  This corrects the CMS ELB configuration to use port 8080.

CMS ELB Healthcheck Target Port Fix

---

gradle.properties
smaas-cf/smaas/support/network.py
smaas-cf/smaas/vpc-and-base.py
src/main/java/com/nike/cerberus/command/core/CreateBaseCommand.java
src/main/java/com/nike/cerberus/domain/cloudformation/BaseParameters.java
src/main/java/com/nike/cerberus/operation/core/CreateBaseOperation.java

removed ec2-compute-domain-name-suffix param from base command as it doesn't actually get used by AWS unless you supply custom name servers and we don't supply a hook for allowing custom name servers when configuring the DHCP options for the Cerberus environment VPC.

removed ec2-compute-domain-name-suffix param from base command

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/com/nike/cerberus/cli/CerberusRunner.java
src/main/java/com/nike/cerberus/command/CerberusCommand.java
src/main/resources/cerberus-lifecycle-cli.properties
src/test/java/com/nike/cerberus/cli/CerberusRunnerTest.java

In reference to Issue #4 I've implemented a -v flag so that users can verify which version of the CLI they are using. 
As -v and --version do not require other parameters the "required" flag had to be removed from environment and region parameters in order for this to properly function. 
Using -v or --version will cause the CLI to ignore any other parameters or commands.

Adds -v flag to the CLI so users can verify the version

---

build.gradle
gradle.properties
src/main/java/com/nike/cerberus/ConfigConstants.java
src/main/java/com/nike/cerberus/cli/CerberusRunner.java
src/main/java/com/nike/cerberus/command/CerberusCommand.java
src/main/java/com/nike/cerberus/module/PropsModule.java
src/main/resources/cerberus-lifecycle-cli.properties
src/test/java/com/nike/cerberus/cli/CerberusRunnerTest.java

- Added @tunderwood's code for version and re-worked the way it loaded props to use Guice so that we can re-use that logic in commands later if needed.
- Re-worked the way region and environment are loaded and verified.
- Re-worked the help messages and error catching to provide a better user experience.
output of -v
old output of typo'ing a command
new output
Also now if you forget a commands required option it will just display the commands usage instead of the usage for every command in the cli

Add version flag and better help messages and re-work region and environment params

---

src/main/java/com/nike/cerberus/cli/CerberusRunner.java
src/main/java/com/nike/cerberus/util/LocalEnvironmentValidator.java

Adding a check for Unlimited Encryption Strength so CLI can fail early when it is not available

Adding a check for Unlimited Encryption Strength

---

smaas-cf/smaas/cms-cluster.py
smaas-cf/smaas/consul-cluster.py
smaas-cf/smaas/gateway-cluster.py
smaas-cf/smaas/vault-cluster.py
src/main/java/com/nike/cerberus/command/StackDelegate.java
src/main/java/com/nike/cerberus/command/core/UpdateStackCommand.java
src/main/java/com/nike/cerberus/domain/cloudformation/LaunchConfigParametersDelegate.java
src/main/java/com/nike/cerberus/operation/cms/CreateCmsClusterOperation.java
src/main/java/com/nike/cerberus/operation/consul/CreateConsulClusterOperation.java
src/main/java/com/nike/cerberus/operation/core/UpdateStackOperation.java
src/main/java/com/nike/cerberus/operation/gateway/CreateGatewayClusterOperation.java
src/main/java/com/nike/cerberus/operation/vault/CreateVaultClusterOperation.java

Adds CLI parameters for desired, max, and min instances in an auto scaling group.

Allow users to specify auto scaling instance counts for cms, consul, gateway, and vault clusters

---

smaas-cf/smaas/cms-cluster.py
smaas-cf/smaas/gateway-cluster.py
smaas-cf/smaas/vpc-and-base.py

CMS and Gateway components are enabled to send signals when services are up.
Add IAM policy as well to enable singals

cms and gateway to use cf signals and required policy changes

---

src/main/resources/example-standup.yaml

People trying out Cerberus may just go with defaults.  Updating example to something we've used.  (We've never even tested min 2 and max 4).
3 or 5 is a good number for number of Consul instances.

Updating example to use min and max of 3 consul instances

---

src/main/java/com/nike/cerberus/command/vault/CreateCmsVaultTokenCommand.java
src/main/java/com/nike/cerberus/operation/vault/CreateCmsVaultTokenOperation.java

Force overwriting existing CMS vault token in secrets.json.  It is important to manually revoke the old CMS token when using this option.

Adding --force-overwrite option to create-cms-vault-token

---

smaas-cf/smaas/cms-cluster.py
smaas-cf/smaas/consul-cluster.py
smaas-cf/smaas/gateway-cluster.py
smaas-cf/smaas/vault-cluster.py
src/main/java/com/nike/cerberus/command/StackDelegate.java
src/main/resources/example-standup.yaml

Updating CloudFormation to keep the min number of instances in service while doing updates (e.g. if you have 3 instances, add a new instance and wait for it to be healthy before removing one of your original 3 instances). This should be a safer way to update Vault and Consul.
This also gives default values in the CloudFormation scripts so that when you update to the new CF the user isn't required to supply values.

Keep the min number of instances in service while updating via CloudFormation

---

gradle.properties
src/main/java/com/nike/cerberus/cli/CerberusRunner.java
src/main/java/com/nike/cerberus/command/consul/UpdateConsulConfigCommand.java
src/main/java/com/nike/cerberus/generator/ConsulConfigGenerator.java
src/main/java/com/nike/cerberus/operation/consul/UpdateConsulConfigOperation.java
src/main/java/com/nike/cerberus/store/ConfigStore.java

Adding command for that updates the consul configuration for the cluster while maintaining the secrets in the current config.
(FYI: the version of consul configuration currently bundled in CLI is compatible with Consul 0.6.4)

Adding update-consul-config command 

---

gradle.properties
src/main/resources/templates/consul-server.json.mustache

- Adding performance settings recommended for Consul 0.7.x or newer
- Setting skip_leave_on_interrupt=false to prevent Consul servers from being marked as 'failed' during rolling update (skip_leave_on_interrupt defaults to true for servers 0.7.x or newer)
- These changes are not compatible with Consul 0.6.4.
More here:
https://www.consul.io/docs/upgrade-specific.html
https://www.consul.io/docs/guides/performance.html
Please delay merging this pull request until we have change for default Consul version merged.

Adding settings needed for Consul 0.7.x or newer 

---

src/main/resources/templates/consul-server.json.mustache

This is related to this change,
https://github.com/Nike-Inc/cerberus-consul-puppet-module/pull/9
The new behavior seemed better at first but after repeated testing I found it wasn't 100% reliable.
It would be good to change these settings back in the future but first, we'd need a new deploy method instead of using CloudFormation for updates.  For example, deploying a new Consul AMI should:
1. Add Consul nodes
2. Wait for them to turn healthy and for the data to be replicated
3. Instruct the old nodes to leave the cluster
4. Wait for them to leave
5. Then shut them down

Changing leave back after finding the related upstart script changes weren't 100% reliable

---

src/main/resources/templates/consul-server.json.mustache

For now, if we add this flag, we can upgrade Consul to version 0.8.x easily using the existing access control policies.
In the future, we need to update our policies,
https://www.consul.io/docs/guides/acl.html#complete-acl-coverage-in-consul-0-8

Adding 'acl_enforce_version_8: false' needed before we upgrade Consul to 0.8.x

---

src/main/resources/templates/consul-client.json.mustache
src/main/resources/templates/consul-server.json.mustache

This is a follow-on to https://github.com/Nike-Inc/cerberus-lifecycle-cli/pull/43

Client also needs 'acl_enforce_version_8: false' before we upgrade Consul to 0.8.x

---

src/main/java/com/nike/cerberus/ConfigConstants.java
src/main/java/com/nike/cerberus/command/cms/CreateCmsClusterCommand.java
src/main/java/com/nike/cerberus/command/consul/CreateConsulClusterCommand.java
src/main/java/com/nike/cerberus/command/core/UpdateStackCommand.java
src/main/java/com/nike/cerberus/command/gateway/CreateGatewayClusterCommand.java
src/main/java/com/nike/cerberus/command/vault/CreateVaultClusterCommand.java
src/main/java/com/nike/cerberus/operation/cms/CreateCmsClusterOperation.java
src/main/java/com/nike/cerberus/operation/consul/CreateConsulClusterOperation.java
src/main/java/com/nike/cerberus/operation/core/UpdateStackOperation.java
src/main/java/com/nike/cerberus/operation/gateway/CreateGatewayClusterOperation.java
src/main/java/com/nike/cerberus/operation/vault/CreateVaultClusterOperation.java
src/main/java/com/nike/cerberus/service/AmiTagCheckService.java
src/test/java/com/nike/cerberus/service/AmiTagCheckServiceTest.java

**Feature: Validate AMI tag before creating or deploying any component**
When creating a new environment or deploying a new component, validate if the given AMI ID has 'cerberus_component' tag and it matches the component name. Fail the deployment when it fails to match this requirement.
By default this check is enforced. Use command option `--skip-ami-tag-check` to skip this check.

Feature: Validate AMI tag before creating or deploying a component

---

gradle.properties
src/main/java/com/nike/cerberus/cli/CerberusRunner.java
src/main/java/com/nike/cerberus/client/CerberusAdminClient.java
src/main/java/com/nike/cerberus/command/cms/UpdateCmsConfigCommand.java
src/main/java/com/nike/cerberus/command/core/RollingRebootWithHealthCheckCommand.java
src/main/java/com/nike/cerberus/command/core/ViewConfigCommand.java
src/main/java/com/nike/cerberus/operation/core/RollingRebootWithHealthCheckOperation.java
src/main/java/com/nike/cerberus/operation/core/ViewConfigOperation.java
src/main/java/com/nike/cerberus/service/AutoScalingService.java
src/main/java/com/nike/cerberus/service/CloudFormationService.java
src/main/java/com/nike/cerberus/service/Ec2Service.java
src/test/java/com/nike/cerberus/service/AutoScalingServiceTest.java
src/test/java/com/nike/cerberus/service/Ec2ServiceTest.java

Adds a command to the CLI that will reboot all CMS instances one by one, ensuring that each one becomes healthy again after reboot.

Feature: Command to Reboot CMS EC2 instances

---

src/main/resources/templates/consul-client.json.mustache
src/main/resources/templates/consul-server.json.mustache

(any value lower than 72 hours seems better when we're using CloudFormation for deploys)

Setting reconnect_timeout to 16 hours

---

smaas-cf/smaas/cms-cluster.py

Increase the grace period to 15 mins to match the CloudFormation signal timeout.

Increase the grace period for CMS to start up

---

src/main/java/com/nike/cerberus/command/cms/UpdateCmsConfigCommand.java
src/main/java/com/nike/cerberus/operation/vault/InitVaultClusterOperation.java

Minor improvements to existing commands:
- `init-vault-cluster` adding helpful log message
- `update-cms-config` clarifying usage of -P parameter

Misc usability improvements

---

smaas-cf/smaas/gateway-cluster.py

- Changing it back because there are possibly some older clients not ready for the new policy.  Will make necessary changes in clients before upgrading to TLSv.1.2

Changing back TLS policy for CloudFront

---

.gitignore
gradle/dependencies.gradle
gradle/integration.gradle
src/integration-test/java/com/nike/cerberus/operation/core/GenerateCertsOperationIntegrationTest.java
src/main/java/com/nike/cerberus/cli/CerberusRunner.java
src/main/java/com/nike/cerberus/command/core/GenerateCertsCommand.java
src/main/java/com/nike/cerberus/operation/core/GenerateCertsOperation.java
src/main/java/com/nike/cerberus/operation/core/UploadCertFilesOperation.java
src/main/java/com/nike/cerberus/service/CertificateService.java
src/main/java/com/nike/cerberus/service/ConsoleService.java

Adding generate cert command that has an Integration Test that is passing with LetsEncrypt ACME api.
This command just creates the files locally and relies on the existing upload cert command to upload to S3 / IAM. Plan is to possibly stream line this once @sdford's changes get merged and I do the rotate command.
Take a look at the Generate Certs Operation Integration Test for my testing methodology.

Add Command to generate Certificate and Keys using BouncyCastle and ACME Providers.

---

src/main/java/com/nike/cerberus/domain/environment/Stack.java
src/main/java/com/nike/cerberus/module/CerberusModule.java

tokenize the environment name in order to support _ chars in env name, which the cli allows when creating environments
I noticed when I made an env called `dev_hl` things broke down.

tokenize the environment name where needed

---

src/main/java/com/nike/cerberus/operation/cms/CreateCmsCmkOperation.java

Do validation in isRunnable rather than run, so it plays nicer with composite commands.
As it is, it will throw a Runtime exception if you try to run the command again without the rotate flag, but it would be nicer if it logged the message and returned false for is runnable so it can be skipped.

Feature/create cms cmk validate in isRunable rather than run

---

src/main/java/com/nike/cerberus/cli/ArgsBuilder.java
src/main/java/com/nike/cerberus/cli/EnvironmentConfigToArgsMapper.java
src/main/java/com/nike/cerberus/command/composite/GenerateAndRotateCertificatesCommand.java
src/main/java/com/nike/cerberus/command/composite/RotateCertificatesCommand.java
src/main/java/com/nike/cerberus/command/core/GenerateCertificateFilesCommandParametersDelegate.java
src/main/java/com/nike/cerberus/command/core/UploadCertificateFilesCommand.java
src/main/java/com/nike/cerberus/command/core/UploadCertificateFilesCommandParametersDelegate.java
src/main/java/com/nike/cerberus/operation/composite/ChainableCommand.java
src/main/java/com/nike/cerberus/operation/composite/GenerateAndRotateCertificatesOperation.java
src/main/java/com/nike/cerberus/operation/composite/RotateCertificatesOperation.java
src/main/java/com/nike/cerberus/operation/core/GenerateCertificateFilesOperation.java
src/main/java/com/nike/cerberus/operation/core/UploadCertificatesFilesOperation.java
src/main/java/com/nike/cerberus/service/CertificateService.java

- Created separate commands for generate-and-rotate-certificates and rotate-certificates to keep required options clean.
- Added flags to enable cert rotation in non-tty environments.
- Added manual flags so cert rotation can be done without YAML.

enable rotation for non-tty environments and with manual option params

---

gradle.properties
src/main/resources/cloudformation/web-app-firewall.yaml

The XSS rule inadvertently blocks valid file and secret POST requests,
returning 403 Forbidden. Prevent this bug by removing the rule.
UPDATE:
Move the XSS rule to the end instead of removing it so we can still take advantage of some of its value.

Removes the AWS WAF XSS rule

---

src/main/java/com/nike/cerberus/cli/EnvironmentConfigToArgsMapper.java
src/main/java/com/nike/cerberus/command/StackDelegate.java
src/main/java/com/nike/cerberus/command/audit/CreateAuditLoggingStackCommand.java
src/main/java/com/nike/cerberus/command/composite/UpdateAllStackTagsCommand.java
src/main/java/com/nike/cerberus/command/core/CreateLoadBalancerCommand.java
src/main/java/com/nike/cerberus/command/core/CreateRoute53Command.java
src/main/java/com/nike/cerberus/command/core/CreateSecurityGroupsCommand.java
src/main/java/com/nike/cerberus/command/core/CreateVpcCommand.java
src/main/java/com/nike/cerberus/command/core/CreateWafCommand.java
src/main/java/com/nike/cerberus/command/core/InitializeEnvironmentCommand.java
src/main/java/com/nike/cerberus/command/core/UpdateStackCommand.java
src/main/java/com/nike/cerberus/command/core/UpdateStackTagsCommand.java
src/main/java/com/nike/cerberus/command/rds/CreateDatabaseCommand.java
src/main/java/com/nike/cerberus/domain/cloudformation/CloudFormationParametersDelegate.java
src/main/java/com/nike/cerberus/domain/cloudformation/GatewayParameters.java
src/main/java/com/nike/cerberus/operation/audit/CreateAuditStackOperation.java
src/main/java/com/nike/cerberus/operation/cms/CreateCmsClusterOperation.java
src/main/java/com/nike/cerberus/operation/composite/UpdateAllStackTagsOperation.java
src/main/java/com/nike/cerberus/operation/core/CreateLoadBalancerOperation.java
src/main/java/com/nike/cerberus/operation/core/CreateRoute53Operation.java
src/main/java/com/nike/cerberus/operation/core/CreateSecurityGroupsOperation.java
src/main/java/com/nike/cerberus/operation/core/CreateVpcOperation.java
src/main/java/com/nike/cerberus/operation/core/CreateWafOperation.java
src/main/java/com/nike/cerberus/operation/core/UpdateStackOperation.java
src/main/java/com/nike/cerberus/operation/core/UpdateStackTagsOperation.java
src/main/java/com/nike/cerberus/operation/rds/CreateDatabaseOperation.java

Renamed Tag Parameters Delegate to CloudFormation Parameters Delegate to better represent that it is generic params delegate for commands that wrap CloudFormation stacks.

Renamed Tag Parameters Delegate to CloudFormation Parameters Delegate

---

src/main/resources/cloudformation/audit.yaml

We need the ability to add additional arns.
This will allow us to have cron jobs on our CI/CD box to generate audit reports for various stake holders.

feat: added ability to supply additional ARNs for audit log bucket perms

---

src/main/resources/cerberus-lifecycle-cli.properties

Avoids showing errors that are part of the normal resolution of the credentials provider chain.

Reduce logging of stack traces that don't matter
